// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTesgZ4lsCn5giS3GJ4O4G5VCHhdsgO44',
    appId: '1:572012092433:web:04a3376ec074582466a5b0',
    messagingSenderId: '572012092433',
    projectId: 'machine-69616',
    authDomain: 'machine-69616.firebaseapp.com',
    storageBucket: 'machine-69616.firebasestorage.app',
    measurementId: 'G-E3D3BQC5QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuCEYJZKf-tsPYD6FBrptdqloWenNFNHM',
    appId: '1:572012092433:android:1dcbf1be04d6163966a5b0',
    messagingSenderId: '572012092433',
    projectId: 'machine-69616',
    storageBucket: 'machine-69616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMgD6Ed6NT6X8GPEzrYl0phcuDIa6wFx0',
    appId: '1:572012092433:ios:142566e2ad93a83866a5b0',
    messagingSenderId: '572012092433',
    projectId: 'machine-69616',
    storageBucket: 'machine-69616.firebasestorage.app',
    iosBundleId: 'com.example.machineTaskk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMgD6Ed6NT6X8GPEzrYl0phcuDIa6wFx0',
    appId: '1:572012092433:ios:142566e2ad93a83866a5b0',
    messagingSenderId: '572012092433',
    projectId: 'machine-69616',
    storageBucket: 'machine-69616.firebasestorage.app',
    iosBundleId: 'com.example.machineTaskk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTesgZ4lsCn5giS3GJ4O4G5VCHhdsgO44',
    appId: '1:572012092433:web:75465712bee47e9066a5b0',
    messagingSenderId: '572012092433',
    projectId: 'machine-69616',
    authDomain: 'machine-69616.firebaseapp.com',
    storageBucket: 'machine-69616.firebasestorage.app',
    measurementId: 'G-4ZVNVH4287',
  );
}
